# Generated by Django 2.2.5 on 2020-01-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Insta', '0002_userconnections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConnections',
            new_name='UserConnection',
        ),
    ]
